<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( 'Test' )->setSeparator( ' - ' )->setAutoEscape( false ); ?>

        <?php echo $this->headMeta()->appendName( 'viewport', 'width=device-width, initial-scale=1.0' ); ?>
        
        <?php echo $this->headLink()
                        ->prependStylesheet( $this->basePath() . '/css/style.css' );
        ?>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
